ALTER TABLE "candles" ALTER COLUMN "volume" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "candles" ALTER COLUMN "open" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "candles" ALTER COLUMN "high" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "candles" ALTER COLUMN "low" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "candles" ALTER COLUMN "close" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "candles" ALTER COLUMN "candle_average" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "candles" ALTER COLUMN "cond_market_twap" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "daos" ALTER COLUMN "slots_per_proposal" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "daos" ALTER COLUMN "twap_initial_observation" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "daos" ALTER COLUMN "twap_max_observation_change_per_update" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "daos" ALTER COLUMN "min_quote_futarchic_liquidity" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "daos" ALTER COLUMN "min_base_futarchic_liquidity" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "indexers" ALTER COLUMN "latest_slot_processed" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "makes" ALTER COLUMN "unfilled_base_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "makes" ALTER COLUMN "filled_base_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "markets" ALTER COLUMN "base_lot_size" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "markets" ALTER COLUMN "quote_lot_size" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "markets" ALTER COLUMN "quote_tick_size" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "markets" ALTER COLUMN "active_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "markets" ALTER COLUMN "inactive_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "unfilled_base_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "filled_base_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "order_block" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "cancel_block" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "prices" ALTER COLUMN "updated_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "prices" ALTER COLUMN "base_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "prices" ALTER COLUMN "quote_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "initial_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "end_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "proposals" ALTER COLUMN "duration_in_slots" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "signatures" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "takes" ALTER COLUMN "base_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "takes" ALTER COLUMN "order_block" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "token_acct_balances" ALTER COLUMN "amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "token_acct_balances" ALTER COLUMN "delta" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "token_acct_balances" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "token_accts" ALTER COLUMN "amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "tokens" ALTER COLUMN "supply" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "transaction_watcher_transactions" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "transaction_watchers" ALTER COLUMN "checked_up_to_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "twaps" ALTER COLUMN "updated_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "twaps" ALTER COLUMN "token_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "user_deposits" ALTER COLUMN "token_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "v0_4_amms" ALTER COLUMN "created_at_slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "v0_4_merges" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "v0_4_splits" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "v0_4_swaps" ALTER COLUMN "slot" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "v0_4_swaps" ALTER COLUMN "input_amount" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "v0_4_swaps" ALTER COLUMN "output_amount" SET DATA TYPE numeric;