-- ALTER TABLE "dao_details" DROP CONSTRAINT "dao_details_base_mint_tokens_mint_acct_fk";
--> statement-breakpoint
-- ALTER TABLE "dao_details" DROP CONSTRAINT "dao_details_quote_mint_tokens_mint_acct_fk";
--> statement-breakpoint
ALTER TABLE "dao_details" ADD COLUMN "dao_acct" varchar(44);--> statement-breakpoint
ALTER TABLE "dao_details" ADD COLUMN "is_active" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "dao_details" ADD COLUMN "is_primary" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "takes" ADD COLUMN "base_decimals" smallint;--> statement-breakpoint
ALTER TABLE "takes" ADD COLUMN "quote_decimals" smallint;
-- ALTER table comments
-- 	ALTER COLUMN comment_id 
-- 	ADD GENERATED BY DEFAULT AS IDENTITY (MINVALUE 1 START WITH 50 INCREMENT BY 1);
-- ALTER TABLE "dao_details" ALTER COLUMN "dao_id" ADD GENERATED BY DEFAULT AS IDENTITY (MINVALUE 1 START WITH 12 INCREMENT BY 1);