name: Build & Push Docker Image 
on:
  push:
    branches: [ main ]
    paths:
      - "**"
jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: themetadao/indexer
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: packages/indexer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  # redeploy_app:
  #   name: Redeploy app on Railway
  #   needs: build_and_push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Call Redeploy API
  #       run: |
  #         curl https://backboard.railway.app/graphql/v2 \
  #         -X POST \
  #         -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
  #         -H "Content-Type: application/json" \
  #         --data "{\"query\":\"mutation { deploymentRedeploy(id: \\\"${{ secrets.RAILWAY_DEPLOYMENT_ID }}\\\") { status } }\"}" \
