name: Run tests before merge
on:
  pull_request:
    branches: [staging]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: bun test
        env:
          RPC_ENDPOINT: https://api.devnet.solana.com/
          BACKUP_RPC_ENDPOINT: https://api.devnet.solana.com/
          INDEXER_URL: https://staging-indexer.metadao.fi
          INDEXER_WSS_URL: wss://staging-indexer.metadao.fi
